app.py
from flask import Flask, request

from views import product_app
app = Flask(__name__)
app.register_blueprint(product_app, url_prefix="/products")
@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        return f"<h1>Hello {request.form.get('name', 'World')}!</h1>"
    return "<h1>Hello world!</h1>"

@app.route("/hello/<string:name>")
def hello(name=None):
    if name is None:
        name = "World"
    return f"<h1>Hello {name}!</h1>"

@app.route("/post/<int:post_id>/")
def show_post(post_id):
    return 'Post %d' % post_id

main.py
from app import app
app.config.update(
    DEBUG=True
)

if __name__ == '__main__':
    app.run(debug=True)

views/__init__.py
from .products import product_app

views/products.py
from flask import Blueprint, render_template
from werkzeug.exceptions import BadRequest

product_app = Blueprint("product_app", __name__)

PRODUCTS = {
    1: 'Smartphone',
    2: 'Tablet',
    3: 'Laptop'
}

@product_app.route("/")
def product_list():
    return render_template('products/index.html', products=PRODUCTS)

@product_app.route("/<int:product_id>/")
def product_detail(product_id: int):
    try:
        product_name = PRODUCTS[product_id]
    except KeyError:
        raise BadRequest(f"Invalid product id #{product_id}")
    return render_template("products/detail.html", product_id=product_id, product_name=product_name,)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base Title
        {% endblock %}
    </title>
</head>
<body>
<div>
{% block body %}
Base Page
{% endblock %}
</div>
</body>
</html>

templates/products/detail.html
{% extends 'base.html' %}

{% block title -%}
Products #={{product_id}}
{%- endblock %}

{% block body %}
<h1>Products {{product_name}}</h1>
<hr>
<a href="{{ url_for('product_app.product_list') }}">Product list</a>
{% endblock %}

templates/products/index.html
{% extends 'base.html' %}

{% block title -%}
Products
{%- endblock %}

{% block body %}
<h1>Products list</h1>
<div>
    <ul>
        {% for product_id in products %}
        <li>
            <a href="{{ url_for('product_app.product_detail', product_id=product_id) }}">
            {{ products[product_id] }}
                </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}